feat: switch to minio operator, add lookup to object store secret
defenseunicorns/uds-package-mattermost pull request #175
Opened 2024-12-03 19:19 UTC by zachariahmiller

## Description

...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-mattermost/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-12-03 21:44 UTC, zachariahmiller commented on chart/values.yaml
> -storage:
i moved this under objectStorage so that it was more aligned. This is inconsistent across apps now, mattermost being one of the outliers, but probably having the convention that makes more sense (objectStorage instead of storage)

I'm happy to make it either and as part of the work to add and validate schemas for the config chart values i would like to standardize on these keys and I plan on writing up a proposal for that, but this issue is happening prior to that work. Open to suggestions on whether to keep this as is or change the netpol stuff back to being under `storage` and then circle back after codifying how we want common patterns in our values. @Racer159

2024-12-03 21:45 UTC, Racer159 commented on chart/values.yaml
> -storage:
I think we can keep it as is and then break it all at once.

2024-12-03 21:46 UTC, ericwyles commented on bundle/uds-bundle.yaml
>    - name: dev-secrets
Do we need to delete this entire reference to dev-secrets package from here?

2024-12-03 21:47 UTC, Racer159 requested changes

2024-12-03 21:47 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +    ref: 6.0.4-uds.1-upstream
```suggestion
    ref: 6.0.4-uds.2-upstream
```

2024-12-03 21:48 UTC, zachariahmiller commented on bundle/uds-bundle.yaml
>    - name: dev-secrets
yeah i thought i already did 🫠

2024-12-03 21:52 UTC, zachariahmiller commented on chart/values.yaml
> -storage:
I'll have to change it back to break it all at once, but sounds good i'll update it.

2024-12-04 18:50 UTC, Racer159 approved these changes

2024-12-04 18:54 UTC, merged