chore: update custom network properties key
defenseunicorns/uds-package-mattermost pull request #178
Opened 2024-12-04 20:50 UTC by codyshoffner

- Updating all instances of `custom: []` to `additionalNetworkAllow: []`

2024-12-04 21:20 UTC, binbashburns approved these changes

2024-12-04 21:27 UTC, zachariahmiller requested changes

2024-12-04 21:27 UTC, zachariahmiller commented on chart/templates/uds-package.yaml
> +      {{- range .Values.additionalNetworkAllow }}
This is not the only place to update. It also needs to be updated [here](https://github.com/defenseunicorns/uds-package-mattermost/blob/83255efc4597ffd019dfb066a3f993c4eb5b1153/chart/values.yaml#L76) and [here](https://github.com/defenseunicorns/uds-package-mattermost/blob/83255efc4597ffd019dfb066a3f993c4eb5b1153/docs/configuration.md?plain=1#L12)

2024-12-06 20:48 UTC, robmcelvenny submitted a review, later dismissed

2024-12-13 19:04 UTC, zachariahmiller approved these changes

2024-12-13 19:05 UTC, merged