chore: standardize repo to template and update README.md
defenseunicorns/uds-package-mattermost pull request #20
Opened 2024-02-05 04:09 UTC by Racer159

This PR updates this repo to meet the repo template set in https://github.com/defenseunicorns/uds-package-sonarqube/pull/32/files

2024-02-05 14:18 UTC, mjnagel commented on CONTRIBUTING.md
> +   > ⚠️ **NOTE:** _:key: We use [Conventional Commit messages](https://www.conventionalcommits.org/) in PR titles so, if you can, use one of `fix:`, `feat:`, `chore:`, `docs:` or similar.  If you nee
```suggestion
   > ⚠️ **NOTE:** _:key: We use [Conventional Commit messages](https://www.conventionalcommits.org/) in PR titles so, if you can, use one of `fix:`, `feat:`, `chore:`, `docs:` or similar.  If you need help, just use `wip:` and we'll help with the rest_
```
I don't know if this was copied in the others but just noticed wording seemed off while scanning.

2024-02-05 14:18 UTC, mjnagel commented on README.md
> +## Pre-requisites
```suggestion
## Prerequisites
```

2024-02-05 14:18 UTC, mjnagel commented on README.md
> +| upstream-ce | Uses upstream images within the package. | `zarf package create . -f upstream` |
```suggestion
| upstream | Uses upstream images within the package. | `zarf package create . -f upstream` |
```

2024-02-05 14:18 UTC, mjnagel commented on README.md
> +2. [/values/values.yaml](/values/values.yaml)
```suggestion
1. [/values/values.yaml](/values/values.yaml)
```

2024-02-05 14:18 UTC, mjnagel commented on README.md
> +## Values
Should we annotate what each of these are? Values for MM helm chart vs UDS config chart?

2024-02-05 14:18 UTC, mjnagel commented on renovate.json
> +        "# renovate: zarf-uri datasource=github-tags depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?\\s.*?uri: ['\"]https:\\/\\/github.com\\/defenseunicorns\\/zarf\\/releases\\/download\\/(?
Not totally clear to me if this is actually tracking anything in this repo?

2024-02-05 14:18 UTC, mjnagel commented on renovate.json
>    "regexManagers": [
I think some of the deletions here mean that we are no longer tracking all dependencies:
- uds-cli
- uds-common-tasks
- zarf (might still be tracked but not clear

2024-02-05 16:33 UTC, mjnagel reviewed
Separate convo but it is blocking this and other PRs - was there a discussion on adding required checks of `Test / Test` here / in other repos? It doesn't match the current workflows so it seems premature to change, also don't love `Test / Test` as the name but whatever gets PRs unblocked is okay.

Edit: we will need to account for the flavors regardless, so maybe `Test / <flavor>` or similar?

2024-02-05 16:36 UTC, zachariahmiller requested changes

2024-02-05 16:36 UTC, zachariahmiller commented on SECURITY.md
> +As UDS Software Factory has not yet reached v1.0.0, only the current latest minor release is supported.
Same comment as the other repo. This is kind of confusing without more information. This repo is tagged/released based on upstream app version and is not in and of itself software factory. At the least, we should provide a link to the repo that has the version that is currently pre-1.0.0 that will eventually be 1.0.0 so that this make sense to others.

2024-02-05 16:50 UTC, zachariahmiller commented
@Racer159 Just a note. The named required checks were changed and they were not changed in this PR, please update the required tests. 

Even if its changed to "Test/Test" it will still fail to pass as there is a matrix on flavors. FWIW I think Test/Test is kind of unnecessary. 

Despite the fact that it is literally testing a deployment (hence Test/Deploy) I understand how "deploy" could mean something more specific to someone. If we are going to change the workflow names lets at least remove the redundancy and allow more room to add additional tests. 

Based on that I'd recommend we update the job names to "Test / <InstallType> <flavor>" for example "Test / Install upstream". That will allow us to, as needed, test upgrades by themselves. Especially for something like gitlab that might be a pain to only test upgrades in the integration repos with the rest of SWF.

2024-02-14 03:44 UTC, Racer159 commented on renovate.json
> +        "# renovate: zarf-uri datasource=github-tags depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?\\s.*?uri: ['\"]https:\\/\\/github.com\\/defenseunicorns\\/zarf\\/releases\\/download\\/(?
it isn't -removed

2024-02-14 03:46 UTC, Racer159 commented on renovate.json
>    "regexManagers": [
we are from the common one now

2024-02-14 03:46 UTC, Racer159 commented on SECURITY.md
> +As UDS Software Factory has not yet reached v1.0.0, only the current latest minor release is supported.
added link

2024-02-14 03:51 UTC, Racer159 commented on README.md
> +## Values
After thinking about it I don't think this is really needed - it will be forgotten and get out of date anyway - I removed it across repos.

2024-02-14 05:23 UTC, zachariahmiller approved these changes
:shipit:

2024-02-14 14:12 UTC, merged