chore: lint
defenseunicorns/uds-package-mattermost pull request #21
Opened 2024-02-05 16:07 UTC by corang

lint project and update pre-commit

2024-02-05 16:24 UTC, mjnagel submitted a review, later dismissed

2024-02-05 16:24 UTC, zachariahmiller requested changes

2024-02-05 16:24 UTC, zachariahmiller commented on .pre-commit-config.yaml
> +            "https://raw.githubusercontent.com/defenseunicorns/zarf/v0.32.2/zarf.schema.json",
@corang If we're going to have a specific version of the schema in this can you please update this with a comment so that renovate will pick up on updates?

2024-02-12 21:40 UTC, Racer159 commented on renovate.json
> +    },
I would recommend we don't do this.  This is going to be very messy long term and instead we should pick a single renovate comment format.

2024-02-15 19:02 UTC, Racer159 commented on renovate.json
> +    },
As of #20 this repo now uses this renovate configuration: https://github.com/defenseunicorns/uds-common/blob/main/config/renovate.json5

This common rule will match this dependency without needing a `# renovate` comment at all: https://github.com/defenseunicorns/uds-common/blob/main/config/renovate.json5#L30

2024-02-15 19:03 UTC, Racer159 commented on renovate.json
> +    },
https://github.com/defenseunicorns/uds-package-mattermost/pull/19/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R43

2024-03-21 21:38 UTC, Racer159 commented
closing as completed in #41

2024-03-21 21:38 UTC, closed without merging