:chore: included workflow to act as shim for docs
defenseunicorns/uds-package-mattermost pull request #27
Opened 2024-02-27 18:43 UTC by naveensrinivasan

## Description

- Included a workflow to act as a shim for docs.

## Related Issue

Fixes #
- https://github.com/defenseunicorns/uds-package-mattermost/issues/25

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-mattermost/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-03-05 22:08 UTC, Racer159 requested changes

2024-03-05 22:08 UTC, Racer159 commented on .github/workflows/ci-docs-shim.yaml
> +      - 'CODEOWNERS'
This list should be the inverse of the tests workflow:

https://github.com/defenseunicorns/uds-package-mattermost/blob/main/.github/workflows/test.yaml
(for this we should probably use the list presented here though since it is more explicit about the _type_ of thing rather than _where_ it is)

2024-03-05 22:08 UTC, Racer159 commented on .github/workflows/ci-docs-shim.yaml
> +  deploy-registry1:
These jobs should have the same names / triggers - this will make a job called `deploy-registry1` which will be different from `Deploy registry1` in the test job - the best way to ensure these are in sync is to use the same job key, name, and matrix as the job it is shimming:
```
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    name: Deploy ${{ matrix.flavor }}
    strategy:
      matrix:
        flavor: [upstream, registry1]
```
https://github.com/defenseunicorns/uds-package-mattermost/blob/8f5d0ccff33edae72e02df88b3b49952eeb2b498/.github/workflows/test.yaml#L23

2024-03-05 22:08 UTC, Racer159 commented on .github/workflows/ci-docs-shim.yaml
> +          echo "Documentation-only change detected; marking deploy upstream as successful."
we should add a lint action for this eventually (some repos have it but not all) but this file doesn't end with a new line)

2024-03-06 17:38 UTC, Racer159 approved these changes
lgtm

2024-03-06 18:08 UTC, Racer159 commented
```
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - ".gitignore"
      - "renovate.json"
      - ".release-please-config.json"
      - "release-please-config.json"
      - "oscal-component.yaml"
      - "CODEOWNERS"
      - "LICENSE"
```
This list may be good to switch to

2024-03-08 20:55 UTC, zachariahmiller requested changes
@naveensrinivasan Where are we at with the changes on this per previous team discussion to move to file types and clean up?

2024-03-11 14:28 UTC, naveensrinivasan commented
> @naveensrinivasan Where are we at with the changes on this per previous team discussion to move to file types and clean up?

@zachariahmiller I will do that. Thank you!

2024-03-11 19:30 UTC, zachariahmiller approved these changes
:shipit:

2024-03-11 19:31 UTC, merged