chore: consolidate workflows to uds-common
defenseunicorns/uds-package-mattermost pull request #36
Opened 2024-03-06 20:27 UTC by ericwyles

## Description

...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-mattermost/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-03-12 18:27 UTC, Racer159 requested changes
partial review before mtg.

2024-03-12 18:27 UTC, Racer159 commented on .github/workflows/tag-and-release.yaml
>          uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
this should also have save-logs after line `55` (it is really useful when things fail)

2024-03-12 19:25 UTC, Racer159 requested changes
rest of comments

2024-03-12 19:25 UTC, Racer159 commented on .github/workflows/test.yaml
>    contents: read
this needs `milestoned` as well (assuming we want to keep that cc @zachariahmiller )

2024-03-12 19:25 UTC, Racer159 commented on tasks.yaml
>        - task: create-test-bundle
We might as well standardize these includes to pull from uds-common v0.2.2 like gitlab

2024-03-12 19:30 UTC, ericwyles commented on .github/workflows/tag-and-release.yaml
>          uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
Added. Used the same suffix pattern from test.yaml.

2024-03-12 19:37 UTC, ericwyles commented on tasks.yaml
>        - task: create-test-bundle
@Racer159 For clarity here... are you suggesting:

1. Update the existing "includes" version numbers to v0.2.2
2. Refactor everything from the 'tasks' folder to also be pulled from uds-common so there are no includes from local paths
3. Something else?

Or all of the above? 

#1 is simple. 

#2 might be nice but I'd probably want to do it in a separate change just to get the benefit of this first round merged while I wrangle what has to happen to move everything out to uds-common for the tasks. As it stands some of these have different tasks that have to execute and I'm not sure how much can be made common on that side just yet. I kept that main 4 task names in the base tasks.yaml as the entry point for CI but they diverge some within the implementation of those 4.

2024-03-12 19:39 UTC, ericwyles commented on .github/workflows/test.yaml
>    contents: read
Added this.

2024-03-12 19:54 UTC, Racer159 commented on tasks.yaml
>        - task: create-test-bundle
number 1, sorry

2024-03-12 19:54 UTC, Racer159 commented on tasks.yaml
>        - task: create-test-bundle
This will get caught with renovate later but just wanted to mention it as a current diff

2024-03-12 19:55 UTC, ericwyles commented on tasks.yaml
>        - task: create-test-bundle
I went ahead and updated it manually. 👍

2024-03-12 20:05 UTC, ericwyles commented
@Racer159 I think this one is ready for another look. It'll need updates from an owner for the 'Required' checks that are listed as 'Expected' now because names changed with the consolidation.

2024-03-13 02:43 UTC, zachariahmiller submitted a review, later dismissed

2024-03-13 02:47 UTC, zachariahmiller commented
@ericwyles updated the required checks for the name change not sure why this one is still showing the old ones... 

anyways this had the docs shim merged and as such will also need the job name for that updated to match the test. https://github.com/defenseunicorns/uds-package-mattermost/blob/5d603fd284f8c366daffff2326b7813669f7c692/.github/workflows/ci-docs-shim.yaml#L32
hopefully fixing that will reset the required checks to the current ones 🤔

2024-03-13 02:59 UTC, zachariahmiller commented
I actually just went and did it so we dont have to think about it tomorrow not sure about the checks though. Will send over to @Racer159 for approval since i now have last commit 😢

2024-03-13 03:06 UTC, Racer159 approved these changes
lgtm (the save logs doesn't have a trailing new line but that's probably fine for now and really a nit)

2024-03-13 03:25 UTC, merged