chore: integrate with keycloak
defenseunicorns/uds-package-mattermost pull request #44
Opened 2024-03-28 18:55 UTC by ericwyles

## Description

...

## Related Issue

Fixes #37 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-mattermost/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-04-22 15:55 UTC, ericwyles commented
It works now without having to manually configure anything, just go to chat.uds.dev, click login with gitlab, redirects you to keycloak. Register yourself a user account and verify email and then chat with yourself.
 
![image](https://github.com/defenseunicorns/uds-package-mattermost/assets/23637493/5affb749-136d-40e0-8346-a4ab9ff40354)

2024-04-22 19:18 UTC, Racer159 requested changes

2024-04-22 19:18 UTC, Racer159 commented on chart/templates/mattermost-sso.yaml
> +kind: Package
This should probably just go into the existing `uds-package.yaml` so we maintain one per package.

2024-04-22 19:18 UTC, Racer159 commented on chart/values.yaml
> +  token_endpoint: "https://sso.###ZARF_VAR_DOMAIN###/realms/uds/protocol/openid-connect/token"
The token endpoint should be able to just use the internal service name (like GitLab does) - userinfo might be able to as well though YMMV - GitLab cannot use the internal url for that.

2024-04-22 19:18 UTC, Racer159 commented on tasks.yaml
> +      - task: test:ingress
I think this is fine but we would want to settle on a name - local-test is probably ok but noticed that sonarqube's PR currently calls it: test-package-app-only

2024-04-22 19:18 UTC, Racer159 commented on tasks.yaml
> +      - task: test:ingress
Eventually this task would use `uds dev deploy` IMO once that is more ready and could be `dev-test` or `test-dev` as well.

2024-04-22 19:26 UTC, ericwyles commented on tasks.yaml
> +      - task: test:ingress
Yep I will rename the sonarqube one to local-test.

2024-04-22 19:52 UTC, ericwyles commented on chart/values.yaml
> +  token_endpoint: "https://sso.###ZARF_VAR_DOMAIN###/realms/uds/protocol/openid-connect/token"
It worked for token but userinfo got a 401 trying to call through the internal service name.

2024-04-22 20:51 UTC, zachariahmiller commented on tasks.yaml
> +      - task: test:ingress
`dev-bundle` 👀

2024-04-22 21:10 UTC, ericwyles commented on tasks.yaml
> +      - task: test:ingress
Renamed it to just `dev` for now and took out the test: tasks

2024-05-03 15:39 UTC, zachariahmiller approved these changes
looks good!

2024-05-03 23:02 UTC, merged