chore: add basic smoke test for mattermost with sso
defenseunicorns/uds-package-mattermost pull request #65
Opened 2024-05-03 23:34 UTC by zachariahmiller

## Description

WIP/Conversation Starter basic test of mm ui.

2024-05-14 21:43 UTC, zachariahmiller reviewed
@marshall007 see comments. It wont let me request changes since i created the PR.

2024-05-14 21:43 UTC, zachariahmiller commented on tests/mattermost-smoketest.spec.ts
> +
```suggestion
  await page.waitForURL(
    /\/preparing-workspace|\/unicorns\/channels\/town-square/,
  );
```

Above got dropped from the end of loginToMattermost(). It either needs to be the last step in that function or called here before setting finalUrl. I tested it in both places again locally and it works for both pre and post setting up the organization.

2024-05-14 21:43 UTC, zachariahmiller commented on package.json
> +{
Can you look at moving the package.json, playwright.config.ts and package-lock.json under the `tests` directory? 

That will help with portability of these tests. That is what was done with gitlab runner as well. 

the commitlint piece in the package.json shouldnt be needed anymore as its pulled in dynamically from the common repo for that ci check

2024-05-14 21:43 UTC, zachariahmiller commented on tasks/test.yaml
> +          npm ci
the actual dependency installation should get moved into the test workflow. See https://github.com/defenseunicorns/uds-package-gitlab-runner/blob/8dbb0eae0c0d574b5105dada4a56c31d78ee730e/.github/workflows/test.yaml#L54

2024-05-14 21:43 UTC, zachariahmiller commented on tasks/test.yaml
> +      - cmd: npx playwright test --project chromium firefox # webkit doesn't retry 421s so fails with login
After you move the other files to the test directory this `cmd:` will need a `dir: test`

2024-05-14 21:43 UTC, zachariahmiller commented on tests/mattermost-smoketest.spec.ts
> +import { test, expect, Page } from "@playwright/test";
for consistency ( i realize i created this in the first place 🤷 ) we should either change this directory to `test` or align on consistently using `test` vs `tests` and update either this repo or the gitlab-runner repo based on that decision

2024-05-14 21:50 UTC, zachariahmiller commented on tests/mattermost-smoketest.spec.ts
> +
i'm just committing this suggestion so the tests will pass...

2024-05-14 22:09 UTC, Racer159 commented on tests/mattermost-smoketest.spec.ts
> +import { test, expect, Page } from "@playwright/test";
I slightly prefer `test` since it allows for more sub folders / organization later on - i.e. with the `journey` folder that GLR has today

2024-05-14 22:44 UTC, Racer159 commented on tests/mattermost-smoketest.spec.ts
> +  }
```suggestion
  }
```

Do we really need this? both flows will wait for this URL in the end

2024-05-14 22:44 UTC, Racer159 commented on playwright.config.ts
> +  workers: process.env.CI ? 1 : undefined,
this defaults to `2` and causes a race condition when run locally.

2024-05-14 22:44 UTC, Racer159 commented on tests/mattermost-smoketest.spec.ts
> +  await sendMessage(page);
this message should be deleted after this since it would be there from previous runs even if a subsequent run failed.

2024-05-14 22:44 UTC, Racer159 commented on tests/mattermost-smoketest.spec.ts
> +  await messageBox.fill('Hello world!');
We should probably add an attachment as well, right now there is no coverage of the minio connection but uploading a small file as an attachment to the message should cover it.

2024-05-15 18:54 UTC, marshall007 commented on package.json
> +{
Good call, done!

2024-05-15 18:56 UTC, marshall007 commented on playwright.config.ts
> +  workers: process.env.CI ? 1 : undefined,
@Racer159 I think I have eliminated race conditions with global `setup` logic. It was not necessary for this package because there is only one test, but will be helpful if we add more.

I tried to make this config file completely portable so we can pull it out into a shared package later. WDYT? /cc @zachariahmiller

2024-05-15 18:59 UTC, marshall007 commented on tasks/test.yaml
> +        dir: tests
I split these out because otherwise `uds run` swallows all useful output.

@zachariahmiller there is still one problem with the `playwright install --with-deps` step. This requires `sudo` and it seems like `uds run` does not prompt for password. It works if you are already root when you run `uds run test:ui`.

2024-05-15 19:01 UTC, marshall007 commented on tests/mattermost-smoketest.spec.ts
> +  await sendMessage(page);
@Racer159 is that really worth doing? I made the tests robust enough to handle multiple runs, but I can insert a random value and check for that instead?

2024-05-15 19:04 UTC, Racer159 commented on tasks/test.yaml
> +        dir: tests
_technically_ it does work, its just the prompt gets swallowed up by the spinner (if you type your password at the right time and hit enter it will work) - we could open an issue to Maru though to better support elevated privileges (or switch to docker containers with a manual call to docker maybe for now)

2024-05-15 20:00 UTC, marshall007 commented on tests/mattermost-smoketest.spec.ts
> +  await sendMessage(page);
Added random values

2024-05-15 20:00 UTC, marshall007 commented on tests/mattermost-smoketest.spec.ts
> +  await messageBox.fill('Hello world!');
I am now uploading an attachment, downloading it, and comparing contents.

2024-05-15 20:03 UTC, marshall007 commented on playwright.config.ts
> +  workers: process.env.CI ? 1 : undefined,
Ok nevermind, Mattermost gets confused sending multiple messages from different workers. I made it `1` everywhere.

2024-05-15 20:08 UTC, marshall007 commented on tests/mattermost-smoketest.spec.ts
> +import { test, expect, Page } from "@playwright/test";
I will leave as `tests` and update elsewhere. I think it makes sense to be plural for the same reasons `tasks` is.

2024-05-15 20:13 UTC, marshall007 commented on tasks/test.yaml
> +        dir: tests
https://github.com/defenseunicorns/maru-runner/issues/88

2024-05-20 20:44 UTC, Racer159 requested changes

2024-05-20 20:44 UTC, Racer159 commented on tests/mattermost.test.ts
> +  // }, 'download completed').toPass();
```suggestion
```

I think this is fine to drop.

2024-05-20 20:44 UTC, Racer159 commented on tests/mattermost.test.ts
> +  // poll channel list in case default channels haven't been created yey
```suggestion
  // poll channel list in case default channels haven't been created yet
```

2024-05-20 20:44 UTC, Racer159 commented on tests/auth.setup.ts
> +  expect(keycloakCookie?.domain).toContain("sso.uds.dev");
```suggestion
  expect(keycloakCookie?.domain).toContain("sso.");
```
we could either drop uds.dev or use process.env here

2024-05-21 14:33 UTC, marshall007 commented on tests/mattermost.test.ts
> +  // }, 'download completed').toPass();
@zachariahmiller found a way to configure MM to not show UI feature tour, so I figured I'd leave it in case we ever get around to disabling that stuff for the tests. The test also works locally if you have logged in as the `doug` user before, so it might help someone debug.

2024-05-21 14:35 UTC, marshall007 commented on tests/mattermost.test.ts
> +  // poll channel list in case default channels haven't been created yey
@Racer159 yey, good suggestion.

2024-05-21 17:44 UTC, Racer159 approved these changes

2024-05-21 18:15 UTC, merged