feat: add oidc option for sso
defenseunicorns/uds-package-mattermost pull request #77
Opened 2024-05-15 21:15 UTC by corang

## Description

...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-mattermost/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-05-15 21:54 UTC, Racer159 requested changes

2024-05-15 21:54 UTC, Racer159 commented on chart/values.yaml
> +  login_button_color: "#145DBF"
This should default to the Defense Unicorns blue as defined in our brand guide.

```suggestion
  login_button_color: "#144A8F"
```

2024-05-15 21:54 UTC, Racer159 commented on chart/templates/uds-package.yaml
> +        MM_GITLABSETTINGS_ENABLE: "false"
why have this env var here?

2024-05-15 21:54 UTC, Racer159 commented on chart/templates/uds-package.yaml
> +        MM_OPENIDSETTINGS_ENABLE: "false"
why have this env var here?

2024-05-15 21:55 UTC, corang commented on chart/templates/uds-package.yaml
> +        MM_GITLABSETTINGS_ENABLE: "false"
Was thinking in the case of moving from oidc -> gitlab or other way around I wanted to be explicit about disabling the other way of signing in

2024-05-15 21:57 UTC, Racer159 commented on chart/templates/uds-package.yaml
> +        MM_GITLABSETTINGS_ENABLE: "false"
Wouldn't this secret get replaced in its entirety and then get merged into the pod spec (thus deleting the other env var set?)

2024-05-15 21:59 UTC, corang commented on chart/templates/uds-package.yaml
> +        MM_GITLABSETTINGS_ENABLE: "false"
Yeah, I'm worried about mattermost itself retaining settings, figured explicit disable was safer just in case

2024-05-15 23:32 UTC, Racer159 commented on chart/templates/uds-package.yaml
> +        MM_GITLABSETTINGS_ENABLE: "false"
Confirmed that it flips without these env vars correctly - there is another issue with the config - will track it down
![image](https://github.com/defenseunicorns/uds-package-mattermost/assets/3977569/6efb0c96-6ce6-4b35-af65-462229b84ddf)

2024-05-15 23:42 UTC, Racer159 commented on chart/templates/uds-package.yaml
> +        MM_GITLABSETTINGS_ENABLE: "false"
When changing sso providers though - MM tracks which users were created from which IDP so any users that used to login with `gitlab` will be disabled from logging in when switching to `openid_connect` based on matching their email address.

2024-05-15 23:46 UTC, Racer159 commented on chart/templates/uds-package.yaml
> +        - "mapper-oidc-email-email"
this needs to be an `if` statement to work correctly:

```
        {{ if eq .Values.sso.protocol "gitlab" }}
        - "mapper-oidc-username-username"
        - "mapper-oidc-mattermostid-id"
        - "mapper-oidc-email-email"
        {{ end }}
        {{ if eq .Values.sso.protocol "openid_connect" }}
        - "profile"
        - "email"
        {{ end }}
```

2024-05-16 02:51 UTC, corang commented on chart/templates/uds-package.yaml
> +        - "mapper-oidc-email-email"
changed as requested

2024-05-16 02:52 UTC, corang commented on chart/templates/uds-package.yaml
> +        MM_GITLABSETTINGS_ENABLE: "false"
Removed unnecessary keys

2024-05-16 14:31 UTC, Racer159 requested changes

2024-05-16 14:31 UTC, Racer159 commented on chart/templates/uds-package.yaml
> +        {{ if eq .Values.sso.protocol "gitlab" }}
```suggestion
        - "openid"
        {{ if eq .Values.sso.protocol "gitlab" }}
```

Sorry I wasn't explicit - openid always needs to be there.

2024-05-16 17:12 UTC, Racer159 approved these changes

2024-05-16 17:12 UTC, merged