chore: add tests to release workflow
defenseunicorns/uds-package-mattermost pull request #85
Opened 2024-06-03 15:59 UTC by ericwyles

## Description

Adds tests before publishing release artifacts

## Related Issue

Fixes #84 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-mattermost/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-06-04 13:49 UTC, Racer159 requested changes

2024-06-04 13:49 UTC, Racer159 commented on tasks.yaml
> -          options: "--skip-sbom"
This is a decent way to save time when running tests for PRs and locally.  It should still be the default.

2024-06-04 13:49 UTC, Racer159 commented on tasks/publish.yaml
> +  - test: ./test.yaml
If we aren't doing these here we don't need these includes.

2024-06-04 13:49 UTC, Racer159 commented on .github/workflows/tag-and-release.yaml
>          run: uds run -f tasks/publish.yaml package --set FLAVOR=${{ matrix.flavor }}
We probably want to untangle these steps to have distinct create, test and publish steps so that they are more modular.

2024-06-04 14:37 UTC, ericwyles commented on .github/workflows/tag-and-release.yaml
>          run: uds run -f tasks/publish.yaml package --set FLAVOR=${{ matrix.flavor }}
Yeah let me peel it apart a little. I might move the arch into the matrix values as well.

2024-06-04 15:24 UTC, zachariahmiller commented on .github/workflows/tag-and-release.yaml
>          run: uds run -f tasks/publish.yaml package --set FLAVOR=${{ matrix.flavor }}
Do we really want to move all of this out to the workflow level though? So we're going from having minimal interaction with github to now having to call multiple different uds run steps and potentially conditionally handle for arch (and only testing on amd64) in the workflows now instead of at the task level, which adds more overhead on the GH side for every repo we make this change in.

2024-06-04 15:26 UTC, zachariahmiller commented on .github/workflows/tag-and-release.yaml
>          run: uds run -f tasks/publish.yaml package --set FLAVOR=${{ matrix.flavor }}
In a case where the ordering of releases had to be staggered we would still need to re-run the create and (if a flavor/arch that gets tested) the tests prior to publish, so I guess im wondering what this gets us not just having this be embedded in the publish tasks other than a dropdown in the github workflow ui.

2024-06-05 14:47 UTC, Racer159 requested changes

2024-06-05 14:47 UTC, Racer159 commented on tasks/publish.yaml
> +  - dependencies: ./dependencies.yaml
lint

2024-06-05 21:18 UTC, closed without merging