Draft: native support for plugins
defenseunicorns/uds-package-mattermost pull request #99
Opened 2024-06-25 18:53 UTC by marshall007

## Description

...

## Related Issue

Fixes #7 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-mattermost/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-06-25 18:55 UTC, marshall007 commented on plugins/Dockerfile
> +ADD https://github.com/mattermost/mattermost-plugin-ai/releases/download/v0.8.2/mattermost-plugin-ai-v0.8.2-linux-amd64.tar.gz /extra-plugins/
This is temporary, I think we should build these as APKs using the melange configs included in this PR.

2024-06-28 19:31 UTC, marshall007 commented
This is ready for review. Should we drop the melange configs from the PR or keep them around for posterity?

2024-06-28 20:09 UTC, Racer159 commented on plugins/ai.melange.yaml
> +package:
This isn't being used right? If so I'd prefer it go as a snippet in an issue to implement later.

2024-06-28 20:10 UTC, Racer159 commented on plugins/gitlab.melange.yaml
> +package:
same with this (bit rot could confuse people later)

2024-06-28 20:15 UTC, Racer159 commented on values/common-values.yaml
> +      emptyDir: {}
is this volume actually wired up?

2024-06-28 20:19 UTC, Racer159 commented on values/common-values.yaml
> +          mountPath: /mattermost/client/plugins/
validating locally but does the extraction put stuff here? (seems odd it would navigate up a directory?)

2024-06-28 21:19 UTC, marshall007 commented on values/common-values.yaml
> +      emptyDir: {}
Nope I needed this on a previous attempt and forgot to remove, thanks!

2024-06-28 21:21 UTC, marshall007 commented on values/common-values.yaml
> +          mountPath: /mattermost/client/plugins/
It's not used for the plugins we are currently shipping. I will remove for now.

2024-07-01 14:44 UTC, marshall007 commented on plugins/ai.melange.yaml
> +package:
Moved to https://gist.github.com/marshall007/5b68cbfcdd6dfc8f2a5e0971c0c0f4d9

2024-07-12 19:01 UTC, zachariahmiller commented on tasks/publish.yaml
> +  # - publish: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.7.1/tasks/publish.yaml
```suggestion
```

2024-07-12 19:14 UTC, marshall007 commented on tasks/publish.yaml
> +  # - publish: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.7.1/tasks/publish.yaml
I'm going to upstream this into `uds-common` so this is coming back.

2024-07-15 20:27 UTC, zachariahmiller requested changes

2024-07-15 20:27 UTC, zachariahmiller commented on values/common-values.yaml
> +# TODO @marshall007: this should work pending: https://github.com/chainguard-images/images/issues/923#issuecomment-2181155300
can we remove this?

2024-07-15 20:27 UTC, marshall007 commented on values/common-values.yaml
> +#   tag: latest
```suggestion
```

2024-07-15 20:28 UTC, zachariahmiller approved these changes
:shipit:

2024-07-15 20:40 UTC, Racer159 requested changes

2024-07-15 20:40 UTC, Racer159 commented on tasks/publish.yaml
> +          done
This is going to publish `dev-secrets` and `namespace` as well for `amd64`.  We should explicitly define which packages we are publishing here.

Also while we _can_ leave this behind I would prefer to upstream this - if not, would request something like:

```
# TODO: @marshall007 - upstream logic into uds-common, tracking: https://github.com/defenseunicorns/uds-common/issues/xyz
```

2024-07-16 16:02 UTC, marshall007 commented on tasks/publish.yaml
> +          done
Ah right, because the workflow runs `test-package` in between `build-package`/`publish-package`. I have implemented the fix here and created https://github.com/defenseunicorns/uds-common/issues/178 to track a solution upstream.

2024-07-16 17:25 UTC, Racer159 approved these changes

2024-07-16 18:03 UTC, merged